import os
import datetime
import sys
from logger.logger import logger
from exception.exception_handling import TripMateException


def save_document(response_text: str, directory: str = "./output"):
    """
    Export travel plan to a Markdown file with proper formatting.
    Args:
        response_text (str): The travel plan content to save
        directory (str): The directory where the file will be saved
    Returns:
        str: The path to the saved file, or None if an error occurs
    """
    try:
        logger.info(f"Saving document to {directory}")
        os.makedirs(directory, exist_ok=True)

        # Create markdown content with metadata header
        markdown_content = f"""# 🌍 TripMate

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""

        # Generate timestamp-based filename
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/Trip_mate_{timestamp}.md"

        logger.info(f"Writing travel plan to {filename}")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(markdown_content)

        logger.info(f"Markdown file saved successfully: {filename}")
        return filename

    except Exception as e:
        error = TripMateException(e, sys)
        logger.error(error.error_message)
        return None
